### PR TITLE
accessiblity changes, responsiveness, color contrast, font family syn…

### LINKED ISSUE #4: Accessibility, Color Contrast, and Page Responsiveness
Adding PR for web component accessibility, with changes related to color contrast and labels for controls.

Also added styling for component responsiveness - styles should grow / shrink according to screen size, with clamped width.

It was difficult to maintain some of the styling and achieve WCAG 2.1 color contrast requirements, so let me know if you're okay with the choices made. We can always try something else if you're not into this presentation 🙂

### PR DESCRIPTION
**Pull request by lee-cooper**
resolves #4 : Accessibility, Color Contrast, and Page Responsiveness

### CODE REVIEW

**Comment by lee-cooper** [comment]
Component
Component-expanded

**Review by bdbrown4 — APPROVED** [review]
Solid refactor of styling! Thank you Lee!!!

**Comment by bdbrown4** [comment]
> Component
> 
> Component-expanded
> 
> 
> 
> 

This new view is much more intuitive! I lack a keen eye in styling!

**Comment by bdbrown4** [comment]
One thing had me thinking, since the style changed we probably want to update the docs gif example with the updated version. I might add this as a TODO for later if you don't get to it in this PR.

**Comment by lee-cooper** [comment]
Added the GIF!

**Pull request merged**
